dcshock/forklift

core/src/main/java/forklift/message/Header.java
that forklift works on. Handling JMS, Stomp, and AMQP. Several headers
we call standard are truly for features in forklift. They are stored as
message properties but we think of them as true headers.
=> Add a class of enum to handle dealing with the different header types

connectors/activemq/src/main/java/forklift/connectors/ActiveMQConnector.java, core/src/main/java/forklift/consumer/Consumer.java, core/src/main/java/forklift/consumer/ConsumerDeploymentEvents.java
Fixes various issues found while investigating forklift.
=> Consumer deployment executor w/ proper consumer shutdown.

DOCKERCONTAINER.md, Dockerfile, core/build.sbt, server/build.sbt
=> create docker container. add fasterxml dependency to build.sbt

core/build.sbt
split out sbt javaOptions to remove linting on javadoc because any javadoc errors will cause the build to fail when compiling with java 8. Add flag to show deprecation warnings when compiling/building.
=> remove javadoc linting and show deprecation warnings

doc/forklift.adoc
Need to add:
```
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "3.0.0")
```
so that this in build.sbt works
```
EclipseKeys.projectFlavor := EclipseProjectFlavor.Java
```
=> Add sbteclipse-plugin as required in plugins.sbt

server/build.sbt
Without this update, the janino stuff doesn't work (allowing for setting environment variable DEV_LOGGING to disable json formatted in logs).
=> Logback library update

connectors/activemq/src/main/java/forklift/producers/ActiveMQProducer.java, connectors/activemq/src/test/java/forklift/activemq/test/ProducerTest.java, core/src/main/java/forklift/producers/ForkliftProducerI.java
The key-value pair Consumer option does not have a corresponding Producer method.
Developer: *"I want to create a producer that can send to SomeConsumer, but I don't have the documentation, lets look at the source."*
```
@Message
Map<String, String> msg;
@OnValidate
public bool validate() {
returm msg.hasKey("a") && msg.hasKey("b");
}
```
Developer: *"Oh, I get it, I just need to send a Map like this."*
```
Map<String, String> msg = new HashMap<>();
msg.set("a", "data1");
msg.set("b", "data2");
forkliftProducer.send(msg);
```
Forklift: `validation failed`
Developer: *???*
The map was serialized as JSON in the Producer, but deserialized as key-value pairs on the Consumer, even though they share the same type.)
Add an additional `send(...)` method so that sending a Map<String, String> …
=> Adding Key Value producer method "send(Map<String, String> ..)"

core/src/main/java/forklift/consumer/Consumer.java, core/src/main/java/forklift/decorators/Ons.java, core/src/test/java/forklift/consumer/OnDecoratorTest.java, doc/forklift.adoc
Fix for https://github.com/dcshock/forklift/issues/71
(Testing annotations is pretty hard. The main pain point is that annotations are read inside Consumer, which then injects them into MessageRunnable, but that injection call is buried deep inside logic that listens to the queues. Might be worth factoring out?)
=> Repeatable @On anntation

.travis.yml
The only difference between my [working builds](https://travis-ci.org/jgsofi/forklift/builds/75168901) and the dcshock [failing builds](https://travis-ci.org/dcshock/forklift/builds/71147633) is that the dcshock TravisCI is still grandfathered in to the old build infrastructure. This upgrades to the new, supposedly faster infrastructure.
=> Opt-in to new travisci infrastructure

connectors/activemq/build.sbt, connectors/activemq/src/test/java/forklift/activemq/test/ResponseTest.java, connectors/kafka/build.sbt, connectors/kafka/src/test/java/forklift/integration/AvroMessageTests.java, connectors/kafka/src/test/java/forklift/integration/BaseIntegrationTest.java, connectors/kafka/src/test/java/forklift/integration/ForkliftMessageTests.java, connectors/kafka/src/test/java/forklift/integration/MapMessageTests.java, connectors/kafka/src/test/java/forklift/integration/ObjectMessageTests.java, connectors/kafka/src/test/java/forklift/integration/StringMessageTests.java, connectors/kafka/src/test/java/forklift/integration/server/TestServiceManager.java
- Improve JUnit test logging (the `-q` option seemed to not give error output sometimes, would use it otherwise)
- Disallow parallel execution for tests of the activemq connector, since they use `TestServiceManager`
- Allow `outOfMessage` handlers in failing tests to have a set number of timeouts before they force the consumer to stop.
- Limit number of messages sent in `ResponseTest` tests, since Circle CI would still go over the timeout limit sometimes
- Give schema-registry 1000 ms to start up (sometimes it just wasn't ready)
Basically, the main problem is that the CI servers are slow, so some delay has to be allowed for in tests. These changes have made the tests pass on Travis and Circle CI as far as I have seen.
----
Please Review: @dcshock @AFrieze
=> Fix Tests on Travis and Circle CI

connectors/kafka/src/test/java/forklift/integration/server/TestServiceManager.java
* Give more retries for connecting to kafka services
* throw an explicit exception when connecting to a service fails (rather than relying on an indirect error later)
=> More Stable Fix for Circle CI tests

core/src/main/java/forklift/consumer/MessageRunnable.java
- If the consumer handler code gives an `InvocationTargetException`, print it as its original error
Just a minor quality of life improvement so that consumer exceptions don't always start with all the `InvocationTargetException` boilerplate.
=> Unwrap InvocationTargetExceptions thrown by consumer

README.adoc, core/build.sbt, core/src/main/java/forklift/concurrent/Executors.java
- Make core thread pool have an unbounded maximum number of threads (essentially a cached thread pool)
We've recently ran into the core thread limit in our project, making it hard to use additional consumers. Since the number of core threads is a static compile-time configuration, it should be fine to make the core thread pool unbounded.
---
Please Review: @dcshock @dthompsn @zdavep @seanmrogers
=> Make core thread pool size unbounded

.gitignore, plugins/retry/build.sbt, plugins/retry/src/main/java/forklift/retry/RetryES.java, server/build.sbt
* A field name was incorrect, causing retries to fail when searching for `connectorName` which should be `destination-connector`
* created some retries for forklift to pick up, confirmed old version failed with `Unable to read result` and that the this version doesn't fail. 
@Kuroshii @dcshock @AFrieze 
Not sure how the versioning of this project works, let me know if I need to make changes.
=> fix connector field name

plugins/replay/src/main/java/forklift/replay/ReplayESWriter.java, plugins/replay/src/main/java/forklift/replay/ReplayLogBuilder.java
- Add a `first-processed-date` property that persists with messages
- Use that `first-processed-date` property to determine the index for a message; no need to do any deleting since elasticsearch's versioning feature provides reliable upserts for us.
For the most part, messages never leave the index they start in, so this helps optimize for that case - after all, dealing with that unconditionally is very excessive. If we really think it's important to move a message to another index when it's reprocessed, I'd recommend moving that kind of logic to forklift-gui.
Ran messages through consumers and observed that the `first-processed-date` property was present in the role message. I changed my local date and retried a message that ended in an errored state and observed that it stayed in the …
=> Optimize out Expensive ES Query in the Replay Plugin

README.adoc, build.sbt, plugins/replay/build.sbt, plugins/replay/src/main/java/forklift/replay/ReplayES.java, plugins/replay/src/main/java/forklift/replay/ReplayESWriter.java, server/src/main/java/forklift/ForkliftServer.java
- Switch from ElasticSearch Transport client to a REST client (a directly REST client, as recommended by elasticsearch)
- Tested running non-erroring messages, without a "replay-version" set in the replay message, delete messages with the same ID in another `forklift-replay*` index and then index a new document in the proper index (ES 2.4 and 5.5).
- Tested ~100 non-erroring messages processing with the latest `replay-version` and observed that they all end up with the final state of `Complete` (ES 2.4 and 5.5)
- Tested that when there is an error, replay messages still end up in an error state (without the version change, out-of-order messages would overwrite final states)
- Tested that the records indexed on the previous day are properly deleted
---
There were some cantankerous …
=> Switch to ES REST client for Replay Messages

README.adoc, doc/PLUGINS.md, server/src/main/java/forklift/ForkliftOpts.java, server/src/main/java/forklift/ForkliftServer.java
- Stop referencing the cluster name in forklift server and doc (make the functional compatibility of ignoring the cluster name more explicit)
- Add note to release notes to better represent the change in protocol
- Fix sample boot script
Please Review: @dcshock
=> Minor cleanup after Replay REST Changes

connectors/kafka/build.sbt, connectors/kafka/src/test/java/forklift/integration/ConsumerActionTests.java, connectors/kafka/src/test/java/forklift/integration/server/KafkaService.java
- Bump kafka versions
- Minor adjustments to test setup to act correctly for Kafka 0.11
There's a fairly big performance impact of using earlier clients when there's a later kafka version because of the cost of down-conversion, so this should generally improve or maintain the old consumer performance.
This should retain compatibility with most versions of Kafka, if I'm reading the [compatibility guide](https://cwiki.apache.org/confluence/display/KAFKA/Compatibility+Matrix) correctly.
----
Please Review: @seanmrogers @AFrieze @dcshock
=> Upgrade Kafka Dependencies to 0.11

connectors/kafka/src/main/java/forklift/controller/AcknowledgedRecordHandler.java, connectors/kafka/src/main/java/forklift/controller/Generation.java, connectors/kafka/src/main/java/forklift/controller/KafkaController.java, connectors/kafka/src/main/java/forklift/message/Generation.java, connectors/kafka/src/main/java/forklift/message/KafkaMessage.java, connectors/kafka/src/test/java/forklift/connectors/AcknowledgedRecordHandlerTests.java, connectors/kafka/src/test/java/forklift/controller/GenerationTests.java, connectors/kafka/src/test/java/forklift/controller/KafkaControllerRebalanceTests.java, connectors/kafka/src/test/java/forklift/message/KafkaMessageTests.java, connectors/kafka/src/test/java/forklift/util/ConsumerRecordCreator.java, connectors/kafka/src/test/java/forklift/util/TestConsumer.java, core/src/main/java/forklift/concurrent/BlockingRejectedExecutionHandler.java, core/src/main/java/forklift/consumer/Consumer.java, core/src/test/java/forklift/concurrent/BlockingRejectedExecutionHandlerTests.java
- Handle rejected executions by blocking to enqueue the rejected message.
- Invalidate records based on a new feature - generation number
- Shutdown consumers faster by emptying the work queue first
- Add test case for duplicate processing records
We are seeing two different kinds of undesired processing: missed messages, and duplicate messages. Below I describe my current reasoning for what is causing these issues and how it can be fixed.
The missed messages seem to be caused by out-of-order processing created by the `CallerRunsPolicy` used for handling messages that can't be queued on the `Consumer` side, combined with a large consumer queue that can't be fully processed in a normal shutdown sequence.
My solution for this is to have rejected executions wait to be queued on the …
=> Fix Kafka Processing Errors

README.adoc, build.sbt, connectors/kafka/src/main/java/forklift/controller/AcknowledgedRecordHandler.java, connectors/kafka/src/main/java/forklift/controller/Generation.java, connectors/kafka/src/main/java/forklift/controller/KafkaController.java, connectors/kafka/src/main/java/forklift/message/Generation.java, connectors/kafka/src/main/java/forklift/message/KafkaMessage.java, connectors/kafka/src/test/java/forklift/connectors/AcknowledgedRecordHandlerTests.java, connectors/kafka/src/test/java/forklift/controller/GenerationTests.java, connectors/kafka/src/test/java/forklift/controller/KafkaControllerRebalanceTests.java, connectors/kafka/src/test/java/forklift/message/KafkaMessageTests.java, connectors/kafka/src/test/java/forklift/util/ConsumerRecordCreator.java, connectors/kafka/src/test/java/forklift/util/TestConsumer.java, core/src/main/java/forklift/concurrent/BlockingRejectedExecutionHandler.java, core/src/main/java/forklift/consumer/Consumer.java, core/src/test/java/forklift/concurrent/BlockingRejectedExecutionHandlerTests.java
* Add release comment
* Bump version number to 3.2
=> Release 3.2

connectors/kafka/src/main/java/forklift/connectors/KafkaConnector.java, connectors/kafka/src/test/java/forklift/connectors/KafkaConnectorTests.java
- Add two public methods `setAddedConsumerProperties` and `setAddedProducerProperties` to allow users of `KafkaConnector` to add (and potentially override) the properties of kafka clients.
This change is pretty straight-forward, and should help handle concerns that crosscut `KafkaConnector` (e.g. security).
----
Please Review: @AFrieze @seanmrogers
=> Allow Adding Additional Parameters for Kafka Clients

doc/forklift.adoc
Simple change after GitHub changed the URL where downloads are stored.
=> GitHub changes the URL for downloads, so update the docs

connectors/kafka/src/main/java/forklift/message/KafkaMessage.java, connectors/kafka/src/test/java/forklift/message/KafkaMessageTests.java, core/src/main/java/forklift/connectors/ForkliftMessage.java, core/src/main/java/forklift/consumer/MessageRunnable.java, core/src/main/java/forklift/consumer/wrapper/RoleInputMessage.java
- Split `ForkliftMessage` acknowledgment into two pieces, one which runs beforehand and can signal messages to be skipped and the other which runs after and is expected to always succeed.
- Made ActiveMQ consumers acknowledge messages after they are processed so as to provide at-least-once processing and avoid dropping messages.
- Tested replay and retry for both AMQ and forklift using a short timeout (10 seconds).
- Noted that messages themselves go over the same queues (the original queue initilaly, and then the role queue for any subsequent messges) and get consumed properly (testing the changes to acknowledging message).
- Noted that the proper entries appear in `forklift-replay` and `forklift-retry` in elasticsearch. That is, the replay index had a message with the message's ID and a …
=> Perform Acknowledgment After Processing When Working with AMQ

Dockerfile, README.adoc, build.sbt, server/src/main/java/forklift/ForkliftOpts.java, server/src/main/java/forklift/ForkliftServer.java
* Add username and password to command line args for forklift-server so we can connect to AMQ that requires a username and password. This will enable us to run forklift-server connecting to AWS AMQ.
* Update forklift version to 3.7
* Tested running forklift-server with:
`forklift-server -url $ACTIVEMQ_OPENWIRE -monitor1 /usr/local/forklift/consumers -monitor2 /config -retryESHost $FORKLIFT_ES_HOST -retryESPort $FORKLIFT_ES_PORT -replayESHost $FORKLIFT_ES_HOST -replayESPort $FORKLIFT_ES_PORT $FORKLIFT_RETRIES` 
* `forklift-server -url $ACTIVEMQ_OPENWIRE -username $SECRET_SERVICE_AMQ_AMQ_USERNAME -password $SECRET_SERVICE_AMQ_AMQ_PASSWORD -monitor1 /usr/local/forklift/consumers -monitor2 /config -retryESHost $FORKLIFT_ES_HOST -retryESPort $FORKLIFT_ES_PORT -replayESHost $FORKLIFT_ES_HOST …
=> Sofi-99339 Add username and password to command line args

connectors/activemq/build.gradle
While 5.16.0 is the latest version of ActiveMQ and our tests pass with this version; Amazon's hosted ActiveMQ solution is currently only at 5.15.12. Downgrading so those using the hosted solution won't run into conflicts.
=> Downgrade to 5.15.12 for compatibility with AWS.
